name: Scrape Table Sums with Playwright

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scrape-and-sum:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm init -y
        npm install playwright
    
    - name: Install Playwright browsers
      run: npx playwright install
    
    - name: Run scraping script by 23f3002416@ds.study.iitm.ac.in
      run: node scrape_tables.js
      env:
        CI: true
